# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ashi-secure-os
description: A completely hermetic, terminal-free, secure study system.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:
  - type: rpm-ostree
    install:
      - fsearch
      - onlyoffice-desktopeditors
      - sayonara
    remove:
      - firefox
      - sudo
      - konsole
      - elisa-player
      - kinfocenter
      - kernel-modules-extra

  - type: script
    scripts:
      - install-zayit.sh
      - hermetic-lock.sh
      - create-shortcut.sh
