# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: roseite
description: RoseiteOS - A completely hermetic, terminal-free, secure study system.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # שינוי השם והגרסה המוצגים במערכת
  - type: os-release
    properties:
      name: "Roseite"
      pretty-name: "Roseite"
      version: "0.2-Alpha"

  - type: script
    scripts:
      - add-repos.sh

  - type: rpm-ostree
    install:
      - onlyoffice-desktopeditors
      - gnome-text-editor
      - gnome-shell-extension-dash-to-dock
#      - https://github.com/digimezzo/dopamine/releases/download/v3.0.2/Dopamine-3.0.2.rpm
    remove:
      # דפדפנים וטרמינל (כולל חבילות השפה)
      - firefox
      - firefox-langpacks
      - gnome-software

      - malcontent-control   # בקרת הורים (GUI)

      - htop
      - nvtop

      - gnome-tour
      - yelp                 # Help (ה־viewer של GNOME)
      - ptyxis                # terminal
      
        
      # רשת וקישוריות (כולל כל הפלאגינים והשירותים)


  - type: script
    scripts:
      - set-defaults.sh
#      - install-zayit.sh
      - install-zmanbar.sh
      - hermetic-lock.sh
